name: SonarQube Analysis

on: [push]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # or 'temurin', 'zulu', etc.

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2856-linux.zip
          unzip sonar-scanner-cli-4.7.0.2856-linux.zip
          sudo mv sonar-scanner-4.7.0.2856-linux /opt/sonar-scanner
          echo "SONAR_SCANNER_HOME=/opt/sonar-scanner" >> $GITHUB_ENV
          echo "PATH=$PATH:$SONAR_SCANNER_HOME/bin" >> $GITHUB_ENV

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your-project-key \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://your-ec2-public-dns:9000 \
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
